chore: Automate Release Pipeline || Test Token Update (#94)
* chore: release pipeline - initial commit

* chore: review changes

* chore: logging for debug - temp

* test: simulate release steps on PR

* chore: pull req target

* feat: tags workflow to automate tagging prior to release

* chore: Checkout Tag Instead of Main

* chore: tagging manually - removed automated workflow

* chore: release-plz change to include a pr creation step on release a new tag

* chore: info add

* chore: crate package path update

* chore: default release path

* chore: add test secrets

diff --git a/.github/workflows/release-plz.yml b/.github/workflows/release-plz.yml
--- a/.github/workflows/release-plz.yml
+++ b/.github/workflows/release-plz.yml
@@ -15,6 +15,16 @@ jobs:
     name: Release-plz release
     runs-on: ubuntu-latest
     steps:
+      - name: Verify TEST_GITHUB_TOKEN and PUBLIC_PACKAGE_GITHUB_TOKEN are set
+        run: |
+          if [ -z "${{ secrets.TEST_GITHUB_TOKEN }}" ]; then
+            echo "Error: TEST_GITHUB_TOKEN is not set or is empty."
+            exit 1
+          fi
+          if [ -z "${{ secrets.PUBLIC_PACKAGE_GITHUB_TOKEN }}" ]; then
+            echo "Error: PUBLIC_PACKAGE_GITHUB_TOKEN is not set or is empty."
+            exit 1
+          fi
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
@@ -26,7 +36,7 @@ jobs:
         with:
           command: release
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
           CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
 
   # Create a PR with the new versions and changelog, preparing the next release.
@@ -37,6 +47,16 @@ jobs:
       group: release-plz-${{ github.ref }}
       cancel-in-progress: false
     steps:
+      - name: Verify TEST_GITHUB_TOKEN and PUBLIC_PACKAGE_GITHUB_TOKEN are set
+        run: |
+          if [ -z "${{ secrets.TEST_GITHUB_TOKEN }}" ]; then
+            echo "Error: TEST_GITHUB_TOKEN is not set or is empty."
+            exit 1
+          fi
+          if [ -z "${{ secrets.PUBLIC_PACKAGE_GITHUB_TOKEN }}" ]; then
+            echo "Error: PUBLIC_PACKAGE_GITHUB_TOKEN is not set or is empty."
+            exit 1
+          fi
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
@@ -48,5 +68,5 @@ jobs:
         with:
           command: release-pr
         env:
-          GITHUB_TOKEN: ${{ secrets.PUBLIC_PACKAGE_GITHUB_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
           CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
